// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fdVBcMZFKfbQD3WsHm8wo
// Component: OWHsT7isVLSVkt
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: YEQmzCtQKI4OO/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent

import { useScreenVariants as useScreenVariantspQljJUlt3Vw4Y8 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: pQljJUlt3Vw4Y8/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_active_compliance.module.css"; // plasmic-import: fdVBcMZFKfbQD3WsHm8wo/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: OWHsT7isVLSVkt/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 85nXgXtej21GKw/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: pqpZPVUtHEq8SY/icon

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  reveal?: p.Flex<typeof Reveal>;
  h1?: p.Flex<"h1">;
};

export interface DefaultHomeProps {}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspQljJUlt3Vw4Y8()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__mNpN9)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__xngoN)}>
                <div className={classNames(projectcss.all, sty.column__nycjm)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__evmPz)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__m8Q7E
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          <React.Fragment>
                            <React.Fragment>{"Quem "}</React.Fragment>
                            {
                              <span
                                className={classNames(
                                  projectcss.all,
                                  projectcss.span,
                                  projectcss.__wab_text,
                                  projectcss.plasmic_default__inline,
                                  sty.span__lmrgo
                                )}
                              >
                                {hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? "somos"
                                  : "marcas "}
                              </span>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        ) : (
                          "Se adeque agora mesmo."
                        )}
                      </h2>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__aFcdJ
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          <React.Fragment>
                            <React.Fragment>{"Quem "}</React.Fragment>
                            {
                              <span
                                className={classNames(
                                  projectcss.all,
                                  projectcss.span,
                                  projectcss.__wab_text,
                                  projectcss.plasmic_default__inline,
                                  sty.span__llTzz
                                )}
                              >
                                {hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? "somos"
                                  : "marcas "}
                              </span>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        ) : (
                          "Sua empresa em compliance com a LGPD em pouco tempo."
                        )}
                      </h2>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__tJ8S
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          <React.Fragment>
                            <React.Fragment>{"Quem "}</React.Fragment>
                            {
                              <span
                                className={classNames(
                                  projectcss.all,
                                  projectcss.span,
                                  projectcss.__wab_text,
                                  projectcss.plasmic_default__inline,
                                  sty.span__h9YMb
                                )}
                              >
                                {hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? "somos"
                                  : "marcas "}
                              </span>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        ) : (
                          "A Active Compliance tem a mais completa, transparente e rápida Adequação LGPD. Entre em contato e saiba como trabalhamos.\n"
                        )}
                      </h2>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___5FglE
                        )}
                        color={"creattorColor" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("#contato" as const)
                            : undefined
                        }
                        shape={"rounded" as const}
                        startIcon={
                          true ? (
                            <ChecksvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__wHapN
                              )}
                              role={"img"}
                            />
                          ) : null
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qWpgn
                          )}
                        >
                          {"Faça seu orçamento"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__dFxr4)}>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__xYo8J
                      )}
                      color={"creattorColor" as const}
                      link={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("#contato" as const)
                          : undefined
                      }
                      shape={"rounded" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__t2Npt
                        )}
                      >
                        {"Saiba mais"}
                      </div>
                    </Button>
                  ) : null}
                </div>
              </div>
            </section>
          ) : null}
          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__gZzNn)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns___75Bm0)}>
                <div className={classNames(projectcss.all, sty.column__m6AI)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yMt3N)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2___4Hccr
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Adequação \nLGPD."
                        : "Adequação \nLGPD."}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oka7Z
                      )}
                    >
                      {"Como funciona?"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x5Nh8
                      )}
                    >
                      {
                        "A Scardino Technology oferece o serviço completo de adequação à LGPD sob medida para empresas de todos os tamanhos."
                      }
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vbS3J
                      )}
                    >
                      {
                        "A adequação das empresas à Lei Geral de Proteção de Dados é uma atividade multidisciplinar, que exige conhecimentos jurídicos e tecnológicos. "
                      }
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__k5GX
                      )}
                    >
                      {
                        "Para isso, atuamos com nossos advogados parceiros oferecendo projetos de adequação para que sua empresa fique em compliance com a legislação de maneira totalmente transparente, onde todos entendem seu papel para a proteção da liberdade e da privacidade dos titulares de dados pessoais."
                      }
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__l1S5)}>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__yFdoP
                      )}
                      color={"creattorColor" as const}
                      link={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("#contato" as const)
                          : undefined
                      }
                      shape={"rounded" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jrBK
                        )}
                      >
                        {"Saiba mais"}
                      </div>
                    </Button>
                  ) : null}
                </div>
              </div>
            </section>
          ) : null}
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__b5CtN)}>
              <Reveal
                data-plasmic-name={"reveal"}
                data-plasmic-override={overrides.reveal}
                className={classNames("__wab_instance", sty.reveal)}
                effect={"zoom" as const}
                triggerOnce={false}
              >
                <section
                  className={classNames(projectcss.all, sty.section__zzVye)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gqo3S)}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Para que um projeto de adequação a Lei Geral de Proteção de Dados seja bem-sucedido, é imperativo que a alta gestão tenha conhecimento sobre a importância da lei e se comprometa a aplicá-la na organização."
                        : "Para que um projeto de adequação a Lei Geral de Proteção de Dados seja bem-sucedido, é imperativo que a alta gestão tenha conhecimento sobre a importância da lei e se comprometa a aplicá-la na organização."}
                    </h1>

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9N0Ru
                        )}
                      >
                        {(
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : true
                        ) ? (
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__itMqQ
                            )}
                            color={"white" as const}
                            link={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? ("#contato" as const)
                                : undefined
                            }
                            shape={"rounded" as const}
                            startIcon={
                              true ? (
                                <ChecksvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__vJrVr
                                  )}
                                  role={"img"}
                                />
                              ) : null
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__iiRmj
                              )}
                            >
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "#000000" }}
                                >
                                  {"Entre em contato"}
                                </span>
                              </React.Fragment>
                            </div>
                          </Button>
                        ) : null}
                      </div>
                    ) : null}
                  </div>
                </section>
              </Reveal>
            </div>
          ) : null}

          <section className={classNames(projectcss.all, sty.section__aap7G)}>
            <div className={classNames(projectcss.all, sty.freeBox___4RCFi)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__g71GP
                )}
              >
                {"Saiba mais sobre as etapas do nosso projeto de \nadequação:"}
              </h2>

              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__dkqAu)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__kFuph)}
                  >
                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__ci56L
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__yzMqv)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/active_compliance/images/group12Png.png",
                          fullWidth: 48,
                          fullHeight: 48,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wok3P
                        )}
                      >
                        {"Fase 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__faCnv
                        )}
                      >
                        {"Formação de Comitê"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oZ8OF
                        )}
                      >
                        {
                          "Primeiramente, conscientizamos todos os gestores da importância da adequação e como ela será feita. Então elaboramos os documentos iniciais do Projeto de Adequação e criamos a estrutura que a empresa utilizará para gerenciar a privacidade e proteção dos dados pessoais sob sua tutela."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w5EtV
                        )}
                      >
                        {
                          "• Comprometimento da Alta Gestão\n• Comunicado a Clientes e Fornecedores sobre adequação à LGPD\n• Projeto Inicial de Implantação e formação de Comitê\n• Pesquisa inicial de soluções tecnológicas\n• Escolha do DPO\n• Desenvolvimento de Apresentação para Multiplicadores\n• Palestras de conscientização de Multiplicadores\n• Lista de Presença e Atualização do Projeto"
                        }
                      </div>
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__kXpFt
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__kBn68)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/active_compliance/images/group12Png.png",
                          fullWidth: 48,
                          fullHeight: 48,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4Af4G
                        )}
                      >
                        {"Fase 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pcTaX
                        )}
                      >
                        {"Formação de Comitê"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pnnbM
                        )}
                      >
                        {
                          "Primeiramente, conscientizamos todos os gestores da importância da adequação e como ela será feita. Então elaboramos os documentos iniciais do Projeto de Adequação e criamos a estrutura que a empresa utilizará para gerenciar a privacidade e proteção dos dados pessoais sob sua tutela."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dse9F
                        )}
                      >
                        {
                          "• Comprometimento da Alta Gestão\n• Comunicado a Clientes e Fornecedores sobre adequação à LGPD\n• Projeto Inicial de Implantação e formação de Comitê\n• Pesquisa inicial de soluções tecnológicas\n• Escolha do DPO\n• Desenvolvimento de Apresentação para Multiplicadores\n• Palestras de conscientização de Multiplicadores\n• Lista de Presença e Atualização do Projeto"
                        }
                      </div>
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__jkK7L
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ofuQu)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/active_compliance/images/group12Png.png",
                          fullWidth: 48,
                          fullHeight: 48,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pBcT6
                        )}
                      >
                        {"Fase 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wmFd
                        )}
                      >
                        {"Formação de Comitê"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jYqoy
                        )}
                      >
                        {
                          "Primeiramente, conscientizamos todos os gestores da importância da adequação e como ela será feita. Então elaboramos os documentos iniciais do Projeto de Adequação e criamos a estrutura que a empresa utilizará para gerenciar a privacidade e proteção dos dados pessoais sob sua tutela."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0TVt
                        )}
                      >
                        {
                          "• Comprometimento da Alta Gestão\n• Comunicado a Clientes e Fornecedores sobre adequação à LGPD\n• Projeto Inicial de Implantação e formação de Comitê\n• Pesquisa inicial de soluções tecnológicas\n• Escolha do DPO\n• Desenvolvimento de Apresentação para Multiplicadores\n• Palestras de conscientização de Multiplicadores\n• Lista de Presença e Atualização do Projeto"
                        }
                      </div>
                    </p.PlasmicLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__xzkVt)}
                  >
                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__vFceM
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hcHYg)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/active_compliance/images/group12Png.png",
                          fullWidth: 48,
                          fullHeight: 48,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1NKmh
                        )}
                      >
                        {"Fase 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pmul2
                        )}
                      >
                        {"Formação de Comitê"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___537Z
                        )}
                      >
                        {
                          "Primeiramente, conscientizamos todos os gestores da importância da adequação e como ela será feita. Então elaboramos os documentos iniciais do Projeto de Adequação e criamos a estrutura que a empresa utilizará para gerenciar a privacidade e proteção dos dados pessoais sob sua tutela."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ySmOx
                        )}
                      >
                        {
                          "• Comprometimento da Alta Gestão\n• Comunicado a Clientes e Fornecedores sobre adequação à LGPD\n• Projeto Inicial de Implantação e formação de Comitê\n• Pesquisa inicial de soluções tecnológicas\n• Escolha do DPO\n• Desenvolvimento de Apresentação para Multiplicadores\n• Palestras de conscientização de Multiplicadores\n• Lista de Presença e Atualização do Projeto"
                        }
                      </div>
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__cW14A
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dOfS6)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/active_compliance/images/group12Png.png",
                          fullWidth: 48,
                          fullHeight: 48,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eVbel
                        )}
                      >
                        {"Fase 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vaReJ
                        )}
                      >
                        {"Formação de Comitê"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rgoIs
                        )}
                      >
                        {
                          "Primeiramente, conscientizamos todos os gestores da importância da adequação e como ela será feita. Então elaboramos os documentos iniciais do Projeto de Adequação e criamos a estrutura que a empresa utilizará para gerenciar a privacidade e proteção dos dados pessoais sob sua tutela."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pHi2L
                        )}
                      >
                        {
                          "• Comprometimento da Alta Gestão\n• Comunicado a Clientes e Fornecedores sobre adequação à LGPD\n• Projeto Inicial de Implantação e formação de Comitê\n• Pesquisa inicial de soluções tecnológicas\n• Escolha do DPO\n• Desenvolvimento de Apresentação para Multiplicadores\n• Palestras de conscientização de Multiplicadores\n• Lista de Presença e Atualização do Projeto"
                        }
                      </div>
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__aOvxh
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__lkz1X)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/active_compliance/images/group12Png.png",
                          fullWidth: 48,
                          fullHeight: 48,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wIEdW
                        )}
                      >
                        {"Fase 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tSiyb
                        )}
                      >
                        {"Formação de Comitê"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b7P9E
                        )}
                      >
                        {
                          "Primeiramente, conscientizamos todos os gestores da importância da adequação e como ela será feita. Então elaboramos os documentos iniciais do Projeto de Adequação e criamos a estrutura que a empresa utilizará para gerenciar a privacidade e proteção dos dados pessoais sob sua tutela."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uEyt9
                        )}
                      >
                        {
                          "• Comprometimento da Alta Gestão\n• Comunicado a Clientes e Fornecedores sobre adequação à LGPD\n• Projeto Inicial de Implantação e formação de Comitê\n• Pesquisa inicial de soluções tecnológicas\n• Escolha do DPO\n• Desenvolvimento de Apresentação para Multiplicadores\n• Palestras de conscientização de Multiplicadores\n• Lista de Presença e Atualização do Projeto"
                        }
                      </div>
                    </p.PlasmicLink>
                  </p.Stack>
                </div>
              ) : null}
            </div>
          </section>

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__wn6Ys)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.freeBox__nTcjA)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__g1SrN
                  )}
                >
                  {"Porque escolher a Active Compliance?\n"}
                </h2>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__stKdl)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dZTp)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___3JQyq)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/active_compliance/images/group11Png.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cjf4F
                      )}
                    >
                      {
                        "Como uma empresa inerentemente tecnológica, temos uma visão abrangente das melhores e mais seguras tecnologias aplicáveis para atendimento à LGPD."
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__co5Ko)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___6X9Kl)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/active_compliance/images/group11Png.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m6LDa
                      )}
                    >
                      {
                        "Como uma empresa inerentemente tecnológica, temos uma visão abrangente das melhores e mais seguras tecnologias aplicáveis para atendimento à LGPD."
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__uWtb1)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gMiBp)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/active_compliance/images/group11Png.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kPpg
                      )}
                    >
                      {
                        "Como uma empresa inerentemente tecnológica, temos uma visão abrangente das melhores e mais seguras tecnologias aplicáveis para atendimento à LGPD."
                      }
                    </div>
                  </div>
                </p.Stack>
              </div>
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "reveal", "h1"],
  reveal: ["reveal", "h1"],
  h1: ["h1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  reveal: typeof Reveal;
  h1: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    reveal: makeNodeComponent("reveal"),
    h1: makeNodeComponent("h1"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
